apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pihole-cloudflared.fullname" . }}
data:
  01-pihole.conf: |
    addn-hosts=/etc/pihole/gravity.list
    addn-hosts=/etc/pihole/black.list
    addn-hosts=/etc/pihole/local.list

    localise-queries

    no-resolv

    cache-size=10000

    log-queries=extra
    log-facility=/var/log/pihole.log

    local-ttl=2

    log-async
    server=127.0.0.1#{{ .Values.service.port.dns }}{{ .Values.service.port.dns }}
    interface=eth0
  external.conf: |
    $HTTP["host"] == "dns.ericbisme.net" {
    # Ensure the Pi-hole Block Page knows that this is not a blocked domain
    setenv.add-environment = ("fqdn" => "true")
    }
  setupVars.conf: |
    DNS_FQDN_REQUIRED={{ .Values.config.setupVars.DNS_FQDN_REQUIRED }}
    DNS_BOGUS_PRIV={{ .Values.config.setupVars.DNS_BOGUS_PRIV }}
    DNSSEC={{ .Values.config.setupVars.DNSSEC }}
    INSTALL_WEB={{ .Values.config.setupVars.INSTALL_WEB }}
    IPV4_ADDRESS={{ .Values.config.setupVars.IPV4_ADDRESS }}
    IPV6_ADDRESS={{ .Values.config.setupVars.IPV6_ADDRESS }}
    LIGHTTPD_ENABLED={{ .Values.config.setupVars.LIGHTTPD_ENABLED }}
    PIHOLE_DNS_1={{ .Values.config.setupVars.PIHOLE_DNS_1 }}
    PIHOLE_DNS_2={{ .Values.config.setupVars.PIHOLE_DNS_2 }}
    PIHOLE_INTERFACE={{ .Values.config.setupVars.PIHOLE_INTERFACE }}
    QUERY_LOGGING={{ .Values.config.setupVars.QUERY_LOGGING }}
