apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole-cloudflared.fullname" . }}-dns-udp
  labels:
    {{- include "pihole-cloudflared.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ template "pihole-cloudflared.fullname" . }}
spec:
  type: {{ .Values.service.type_dns }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP_dns }}
  ports:
    - name: dnsudp
      port: {{ .Values.service.port.dns }}
      protocol: UDP
    - name: cloudflared
      port: {{ .Values.service.port.dns }}{{ .Values.service.port.dns }}
      protocol: UDP
  selector:
    app: {{ template "pihole-cloudflared.name" . }}
    release: {{ .Release.Name }}
