{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pihole-cloudflared.serviceAccountName" . }}
  labels:
{{ include "pihole-cloudflared.labels" . | nindent 4 }}
{{- end -}}
