apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole-cloudflared.fullname" . }}
  labels:
    {{- include "pihole-cloudflared.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port.http }}
      protocol: TCP
    - name: https
      port: {{ .Values.service.port.https }}
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.port.metrics }}
      protocol: TCP
  selector:
    {{- include "pihole-cloudflared.selectorLabels" . | nindent 4 }}
